from django.db import models
from login.managers import activeSessionsManager, UserSessionsManager, loginHistoryManager

class client(models.Model):
    sno                          = models.AutoField(primary_key=True)
    agency_id                    = models.IntegerField(default=1)
    alias                        = models.CharField(default="TT", max_length=10, unique=True)
    client_name                  = models.CharField(max_length=100,unique=True)
    created_date                 = models.BigIntegerField(null=False, blank=False, default=0)
    enabled_services             = models.CharField(max_length=100, default='IDR,BULK,CFACE')
    hit_limit                    = models.IntegerField(default=2)
    report_download_permission   = models.IntegerField(default=1)#0 means not showing download option 1 means showing
    user_agents                  = models.CharField(max_length=40, default="MOBILE,SMARTPHONE,TABLET,COMPUTER,BOT")

class users(models.Model):
    sno                      = models.AutoField(primary_key=True)
    client_name              = models.CharField(max_length=50, null=False, blank=False)
    contact_number           = models.CharField(max_length=15, null=False, blank=False)
    state                    = models.CharField(max_length=25)
    user_name                = models.CharField(max_length=150)
    user_type                = models.CharField(max_length=15)
    created_date             = models.BigIntegerField(null=False, blank=False, default=0)
    email_address            = models.EmailField(blank=False,null=False,default="example@example.com")
    enabled_apis             = models.JSONField(null=True, blank=True, default=dict)
    enabled_services         = models.CharField(max_length=100, default='IDR,BULK,CFACE')
    login_id                 = models.BigIntegerField(null=False, blank=False, default=1901000000, unique=True)
    password                 = models.CharField(max_length=128)
    ip_check_flag            = models.BooleanField(null=False, blank=False, default=False)
    admin_adding             = models.BooleanField(null=False, blank=False, default=False)
    api_key                  = models.CharField(null=True, blank=False, max_length=48)
    application_quota        = models.IntegerField(default=500)
    boss_id                  = models.BigIntegerField(default=1)
    login_active             = models.BooleanField(null=False, blank=False, default=True)
    office_address           = models.TextField(blank=False)
    otp_class_flag           = models.BooleanField(null=False, blank=False, default=False)
    registered_ip_address    = models.CharField(max_length=45, null=False, blank=False, default="0000:0000:0000:0000:0000:0000:0000:0000")
    residential_address      = models.TextField(blank=False)
    session_active           = models.BooleanField(null=False, blank=False, default=False)
    session_system_info      = models.CharField(max_length=75)
    session_last_activity_ts = models.BigIntegerField(null=False, blank=False, default=0)
    verticals                = models.CharField(max_length=50)
    created_login_id         = models.BigIntegerField(null=False, blank=False, default=1901000000)
    otp_count                = models.IntegerField(default=0)
    reset_password_count     = models.IntegerField(default=0)
    incorrect_password_count = models.IntegerField(default=0)
    objects = activeSessionsManager()

class request_process(models.Model):
    sno              = models.AutoField(primary_key=True, null=False, blank=False)
    login_id         = models.CharField(max_length=15, default="1901000000", null=False, blank=False)
    record_id        = models.CharField(max_length=65, default="abcde000000000000000000000000000_000000000000000000000000000vwxyz", null=False, blank=False)
    application_no   = models.CharField(max_length=75, null=False, blank=False, default="UNDEFINED")
    service_progress = models.JSONField(null=False, blank=False, default=dict)
    state            = models.CharField(null=False, blank=False, max_length=45, default="Delhi")
    processing_flag  = models.BooleanField(null=False, blank=False, default=False)
    product          = models.CharField(null=False, blank=False, max_length=75, default="Personal Loan")
    results_viewed   = models.BooleanField(null=False, blank= False, default=False)
    timestamp        = models.BigIntegerField(null=False, blank=False, default=0)
