# Generated by Django 5.1.3 on 2025-01-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('agency_id', models.IntegerField(default=1)),
                ('alias', models.CharField(default='TT', max_length=10, unique=True)),
                ('client_name', models.CharField(max_length=100, unique=True)),
                ('created_date', models.BigIntegerField(default=0)),
                ('enabled_services', models.CharField(default='IDR,BULK,CFACE', max_length=100)),
                ('hit_limit', models.IntegerField(default=2)),
                ('report_download_permission', models.IntegerField(default=1)),
                ('user_agents', models.CharField(default='MOBILE,SMARTPHONE,TABLET,COMPUTER,BOT', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='request_process',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('login_id', models.CharField(default='1901000000', max_length=15)),
                ('record_id', models.CharField(default='abcde000000000000000000000000000_000000000000000000000000000vwxyz', max_length=65)),
                ('application_no', models.CharField(default='UNDEFINED', max_length=75)),
                ('service_progress', models.JSONField(default=dict)),
                ('state', models.CharField(default='Delhi', max_length=45)),
                ('processing_flag', models.BooleanField(default=False)),
                ('product', models.CharField(default='Personal Loan', max_length=75)),
                ('results_viewed', models.BooleanField(default=False)),
                ('timestamp', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=25)),
                ('user_name', models.CharField(max_length=150)),
                ('user_type', models.CharField(max_length=15)),
                ('created_date', models.BigIntegerField(default=0)),
                ('email_address', models.EmailField(default='example@example.com', max_length=254)),
                ('enabled_apis', models.JSONField(blank=True, default=dict, null=True)),
                ('enabled_services', models.CharField(default='IDR,BULK,CFACE', max_length=100)),
                ('login_id', models.BigIntegerField(default=1901000000, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('ip_check_flag', models.BooleanField(default=False)),
                ('admin_adding', models.BooleanField(default=False)),
                ('api_key', models.CharField(max_length=48, null=True)),
                ('application_quota', models.IntegerField(default=500)),
                ('boss_id', models.BigIntegerField(default=1)),
                ('login_active', models.BooleanField(default=True)),
                ('office_address', models.TextField()),
                ('otp_class_flag', models.BooleanField(default=False)),
                ('registered_ip_address', models.CharField(default='0000:0000:0000:0000:0000:0000:0000:0000', max_length=45)),
                ('residential_address', models.TextField()),
                ('session_active', models.BooleanField(default=False)),
                ('session_system_info', models.CharField(max_length=75)),
                ('session_last_activity_ts', models.BigIntegerField(default=0)),
                ('verticals', models.CharField(max_length=50)),
                ('created_login_id', models.BigIntegerField(default=1901000000)),
                ('otp_count', models.IntegerField(default=0)),
                ('reset_password_count', models.IntegerField(default=0)),
                ('incorrect_password_count', models.IntegerField(default=0)),
            ],
        ),
    ]
