# Generated by Django 5.1.3 on 2025-01-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event_log',
            fields=[
                ('sno', models.BigAutoField(primary_key=True, serialize=False)),
                ('datetime', models.BigIntegerField(default=1901000000)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('login_id', models.CharField(default='1901000000', max_length=10)),
                ('log_level', models.CharField(default='INFORMATION', max_length=12)),
                ('module', models.CharField(blank=True, max_length=33)),
                ('resource_id', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='transactions_log',
            fields=[
                ('sno', models.BigAutoField(primary_key=True, serialize=False)),
                ('trx_id', models.CharField(default='ABC123', max_length=100)),
                ('api_id', models.CharField(default='RC', max_length=15)),
                ('appl_no', models.CharField(default='UNDEFINED', max_length=75)),
                ('product', models.CharField(default='Personal Loan', max_length=75)),
                ('state', models.CharField(default='Delhi', max_length=45)),
                ('login_id', models.BigIntegerField(default=1901000000)),
                ('bill_slab', models.CharField(default='A', max_length=2)),
                ('billable', models.BooleanField(default=False)),
                ('resp_code', models.CharField(default='101', max_length=5)),
                ('timestamp', models.BigIntegerField(default=0)),
                ('trx_type', models.CharField(default='BULK', max_length=12)),
                ('response_metadata', models.JSONField(default=dict)),
                ('source_resp_time', models.CharField(default='ABC123', max_length=50)),
                ('overall_resp_time', models.CharField(default='ABC123', max_length=50)),
            ],
        ),
    ]
